// let marks =[97,34,56,78,87];
// console.log(marks);
// console.log(marks.length);
// let fruits=["apple","mango","grapes","kiwi"];
// console.log(fruits);
// console.log(fruits.length);
// console.log(typeof(marks));
// console.log(typeof(fruits));

// //array indices
// console.log(marks[0]);
// console.log(fruits[0]);

// for(let i=0;i<fruits.length;i++){
//     console.log(fruits[i]);
// }

//for of

// for(let fruit of fruits){
//     console.log(fruit);
// }

//Uppercase
// for(let fruit of fruits){
//     console.log(fruit.toUpperCase());
// }

// //sum and avg
// let sum =0;
// for (let val of marks){
//     sum=sum+val;
// }

// let avg =sum/marks.length;
// console.log(sum);
// console.log(avg);

//quesion1
// let marks_of_student=[85,97,44,37,76,60];
// let sum1 =0;
// for(let val of marks_of_student){
//     sum1 =sum1+val;
// }
// console.log(sum1);
// let avg=sum1/marks_of_student.length;
// console.log(avg);

//question2

// let price = [250, 645, 300, 900, 50];
// console.log(price);
// for (let i = 0; i < price.length; i++) {
//     let offer = price[i] / 10;
//     price[i] -= offer;
// }
// console.log(price);




//push= add to end
// console.log(fruits.push("banana"));
// console.log(fruits);
// //pop= delete from end and return
// console.log(fruits.pop());
// console.log(fruits);
//tostring=convert array to string
// console.log(fruits.toString());
//concat = join multiple array
// console.log(marks.concat(fruits));
// // console.log(fruits);
// //unshift = add to start
// console.log(fruits.unshift("grapes"));
// console.log(fruits);
// //shift=delete from start
// console.log(fruits.shift());
// console.log(fruits);

// slice = retun a piece of the array
// console.log(fruits.slice(1,3));
// // splice= change original array
// console.log(marks.splice(0,2,23));


// let array=["bloomberg","microsoft","uber","google","ibm","netflix"];
// // array.shift();
// // console.log(array);
// // array.splice(0,2,"ola");
// // console.log(array);
// array.push("amazon");
// console.log(array);