// let age=5;
// let grace=8;

// console.log(age+grace);

// if((age+grace+7)>18)
// {
//     console.log("you can drive");
// }
// else if(age ==0)
// {
//     console.log("r u kid");
// }
// else {
//     console.log("you cannot drive");
// }


// a=6;
// b=8;
// let c = a > b ? (a - b) : ( b - a);
// console.log(c);



// let a=2;
// let b=5;
// let c="5";
// console.log(a+b);
// console.log(a-b);
// console.log(a*b);
// console.log(a/b);
// console.log(a**b);
// console.log(b==c);
// console.log(b===c);





// alert ("hello");
// let num = 9;//prompt("enter aa number");
// if(num>5){
//     console.log("greter");
// }
// else{
//     console.log("less");
// }




