// function nice(name) {
//     console.log("hey " + name + " you are nicel");
//     console.log("hey " +  name+ " you are good");
//     console.log("hey " + name + " you are awsome");
//     console.log("hey " + name + " you are abd");
//     console.log("hey " + name + " you are nic0el");   
// }

// nice("rohan")
// nice("shivam")


// function sum(a,b,c=3) {
//     // console.log(a+b);
//     return a+b+c
// }
// result =sum(1,2,1)
// result2 =sum(6,5)
// console.log("the sum =",result);
// console.log("the sum =",result2);


// const func1 = (x)=>{
//     console.log("i am an arrow function",x)
// }

// func1(34);
// func1(67);


// function myfunction(msg){
//     console.log(msg);
// }

// myfunction("i love india");
// myfunction("i love myself");
// myfunction("i love my family");


