// let a=1;
// for(let i=0;i<100;i++){
//     console.log(a+i);
// }


// let obj={
//     name :"harshita",
//     role : "student",
//     company : "university"
// }


// //for in
// for (const key in obj) {             //for objects
//         const element = obj[key];
//         console.log(key,element)   
//     }


//for of
// let size = 0;
// for (const c of "harshita") {    //for string and array use
//     console.log(c);
//     size++;
// }
// console.log(size);



// let i=1;
// while (i<6){
//     console.log(i)
//     i++;
// }


// i=0
// do {
//     console.log(i)
//     i++
// } while (i<5);


//game
// let gamenum = 25;
// let usernum=prompt("guess the game num.");

// while(usernum!=gamenum){
//     usernum=prompt("u entered wrong number guess again");
// }

// console.log("u win the game");


