// let a=1;
// for(let i=0;i<100;i++){
//     console.log(a+i);
// }

// let obj={
//     name :"harshita",
//     role : "student",
//     company : "university"
// }
// for (const key in obj) {
//         const element = obj[key];
//         console.log(key,element)   
//     }
// for (const c of "harshita") {
//     console.log(c);
// }

// let i=1;
// while (i<6){
//     console.log(i)
//     i++;
// }


// i=0
// do {
//     console.log(i)
//     i++
// } while (i<5);