// const user ={
//     name : 'Harshita',
//     age : 19,
//     stream : 'CSE',
// };
// user.name='Harshita Goyal';
// console.log(user);
// console.log(user.age);





const users={
    user1:{name : 'abs',
        class:78,
    },

    user2:{
        name:'htg',
        class:67,
    },
    user3:{
        name:'ghjk',
        class:56,
    }
};

console.log(users);
console.log(users.user1);
console.log(users['user2']);




