// let str = "Apna College";                            //strings are immutable they cannot change value
// console.log(str);                    //create string

// let str1="abcd";

// console.log(str.length);               //length
// console.log(str[1]);                    //indices
// console.log(str.toUpperCase());
// console.log(str.toLowerCase());
// console.log(str.trim());                  //remove whitespaces (first and last spaces)
// console.log(str.slice(1,8));              //returns part of string
// console.log(str.concat(str1));
// console.log(str.replace("A","M"));
// console.log(str.charAt(0));      //to find character
// let message = "An idiot in the class always do ruckus. ";
// console.log(message.repeat(3));




//template literals

// let str=`this is template literals`;
// console.log(typeof str);




// let obj={
//     item : "pen",
//     price : 10,
// };

// let output = `the cost of ${obj.item} is ${obj.price} rupees`;

// console.log(output);


// let userName=prompt("enter the full name");
// console.log("@"+userName+userName.length);
