// console.log("Hey this is jsavascript")

// // let is a  block scope
// // var is a global scope
// let a=5;
// let b=10;
// // this is aloud
// a=a+11;
// let c="Harshita";

// console.log(a+b+8)
// console.log(a)
// console.log(typeof a,typeof b, typeof c)

// // const a1 =6;
// // not aloud
// // a1=a1+5;







//APNA COLLEGE


console.log("apna college");
console.log("i love myself");
age=24;
console.log(age);
console.log(typeof(age));


//can be redeclare and updated
var n_ame = "Harshita";
console.log(n_ame);


//cannot be redeclare but updated
let name = "Harshita";
console.log(name);


//cannot be redeclare or updated and must be declare once
const na_me = "Harshita";
console.log(na_me);


//7 primitive datatypes

let x="Harshita";
let y=22;
let z=3.33;
const p=true;
let q=undefined;
let r=null;

console.log(x,y,z,p,q,r)
console.log(typeof x,typeof y,typeof z,typeof p,typeof q,typeof r)

//non primitive is object data type (means collection of values)like string, array etc.

const o={
    name : "Harry",
    job_code : 5600,
    is_handsome : true
}
o.name="Moorvi";
o.salary = "100crores";
console.log(o.name);
console.log(typeof(o));


const product={
    name : "amazon",
    rating : 4,
    offer :"20%",
    price:270,
};

console.log(product);
console.log(typeof product["rating"]);

